export default {
  GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS",
  GET_TOKEN_FAIL: "GET_TOKEN_FAIL",
  GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
  GET_BANNER_FAIL: "GET_BANNER_FAIL",
  GET_PLAY_LIST_SUCCESS: "GET_PLAY_LIST_SUCCESS",
  GET_PLAY_LIST_FAIL: "GET_PLAY_LIST_FAIL",
  GET_EXCLUSIVE_LIST_SUCCESS: "GET_EXCLUSIVE_LIST_SUCCESS",
  GET_EXCLUSIVE_LIST_FAIL: "GET_EXCLUSIVE_LIST_FAIL",
};
